### ISSUE TITLE
[Question] Why is <unk> token tokenized into 3 items?

### ISSUE THREAD

**Issue by MarkusSpanring** [hplt-project/sacremoses#136]
I noticed when `moses` encounters the `<unk>` token as used e.g. in the `PennTreebank` or `WikiText2` dataset it splits it into three items:
```python
from sacremoses import MosesTokenizer
mt = MosesTokenizer()
mt.tokenize("My name is <unk>")
>>> ['My', 'name', 'is', '&lt;', 'unk', '&gt;']
```
Similar for the hyphen e.g. in
```python
from sacremoses import MosesTokenizer
mt = MosesTokenizer()
mt.tokenize("tactical and real @-@ time gameplay")
>>> ['tactical', 'and', 'real', '@', '-', '@', 'time', 'gameplay']
```
I would expect that these items stay joined. Especially the `<unk>` token.
Is this the expected behaviour?

**Comment by jelmervdl** [comment]
(Sorry, bit late, mostly saying this for people who might search for it.)

This is expected, yes. The tokenizer doesn't know about tokens with special meaning. To it, everything is just text. To be honest, the `@-@` already looks as if it was tokenized as that is one of the things the tokenizer generates when you enable aggressive hyphen split.

If you want to treat these tokens differently, there's an option to add protected patterns when calling `tokenize()`:

```py
mt = MosesTokenizer()
mt.tokenize('My name is <unk> and I am into real @-@ time gameplay',
  escape=False,
  protected_patterns=[r'\<unk\>', r'@-@'])
>>> ['My', 'name', 'is', '<unk>', 'and', 'I', 'am', 'into', 'real', '@-@', 'time', 'gameplay']
```
